# Generated by Django 2.2 on 2021-08-06 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20210802_1541'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='avaliable',
            new_name='available',
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.categ'),
        ),
    ]
